name = input("Enter your name: ")
age = input("Enter your age: ")
location = input("Enter your location: ")
#print(name, age, location)
print("My name is",name, ",")
print("I am",age, "years old",",")
print("I am form", location,",")
